prSections:
- title: Platform Team PRs
  filters: is:pr is:open -is:draft author:ibrahimbadivi author:SamuASantana author:DenysPoznukhovNiX author:dthorne author:ashevchuk-ecw author:FloLys author:rgowdacricut -reviewed-by:@me
  type: null
- title: Needs My Review
  filters: is:open review-requested:@me -reviewed-by:@me 
  type: null
issuesSections:
- title: Involved
  filters: is:open involves:@me -author:@me
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  preview:
    open: true
    width: 80
  prsLimit: 30 
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal: []
  issues: []
  prs:
    - command: |
        tmux split-window -h -c {{.RepoPath}} 'zsh -i -c "gh pr checkout {{.PrNumber}} && nvim -c \":Octo pr edit {{.PrNumber}}\""'
      key: C
    - command: |
        tmux split-window -h 'zsh -i -c "gh repo clone {{.RepoName}} /Users/dmcneill/src/{{.RepoName}}"'
      key: V
  branches: []
repoPaths:
  cricut/*: ~/src/cricut/*
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
pager:
  diff: ""
confirmQuit: true
showAuthorIcons: true
smartFilteringAtLaunch: false
